### ISSUE TITLE
Source not Loading

### ISSUE THREAD

**Issue by IeUDE** [vadash/VmsHelper#1]
For some reason the PlugIn ain't loading for me -- using latest ExileApi, i.e. PoEHelper I compiled myself.

Followed instructions, i.e. put the PlugIn folder under ."..\PoEHelper\Plugins\Source\"

```
C:\PHuD\PoEHelper\Plugins\Source\VmsHelper\CoreUpdate.cs(13,33) : error CS0453: The type 'ActorVaalSkill' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'
C:\PHuD\PoEHelper\Plugins\Source\VmsHelper\CoreUpdate.cs(24,29) : error CS0453: The type 'List<Buff>' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'
C:\PHuD\PoEHelper\Plugins\Source\VmsHelper\Core.cs(26,45) : error CS0453: The type 'TimeCache<ActorVaalSkill?>' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'
C:\PHuD\PoEHelper\Plugins\Source\VmsHelper\Core.cs(26,45) : error CS0453: The type 'ActorVaalSkill' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Nullable<T>'
```

**Comment by vadash** [comment]
Hey. Are u using TC fork ? Here is compiled
[VmsHelper.zip](https://github.com/vadash/VmsHelper/files/5096334/VmsHelper.zip)

**Comment by IeUDE** [comment]
> Hey. Are u using TC fork ? Here is compiled
> [VmsHelper.zip](https://github.com/vadash/VmsHelper/files/5096334/VmsHelper.zip)

Yes, TC-ExileAPI -- which one do you use, i.e. should be used for this plugin to work (from source)?

**Comment by vadash** [comment]
Yep I fucked up. It doesnt work from source
